version: "3.8"

volumes:
  library_db:

services:
  ams-database:
    image: postgres:14.4-alpine
    restart: unless-stopped
    container_name: db.library.com
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      retries: 3
    ports:
      - "5436:5432"
    volumes:
      - library_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: libraryadmin123

