spring:
  application:
    name: demo-application
  datasource:
    url: jdbc:postgresql://localhost:5436/library
    username: adminuser
    password: libraryadmin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true